# Agent Execution Script - company_associations
# Generated by Agent Factory for Phase: timesheet_creation
# Generated: 2025-09-18 15:06:29

param(
    [Parameter(Mandatory=$false)]
    [string]$Action = "execute"
)

# Import shared utilities
$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$sharedPath = Resolve-Path "$scriptPath/../../../../shared"
Import-Module "$sharedPath/agent-utilities.psm1" -Force

# Agent configuration
$Configuration = @{
{
  "processing": {
    "validation_rules": [
      {
        "parameters": {
          "Metadata": "companies_metadata",
          "ObjectName": "Companies"
        },
        "type": "required_properties"
      }
    ],
    "create_directories": [
      "properties",
      "assets",
      "workflows",
      "backend",
      "frontend"
    ],
    "output_files": [
      {
        "data_source": "companies_metadata",
        "transform": {
          "Attributes": [],
          "File": "D:\\code\\hjpshubspot\\analysis\\\\timesheet_process\\\\shared\\agent-configurations.ps1",
          "IsFilter": false,
          "IsConfiguration": false,
          "Module": null,
          "StartPosition": {
            "Content": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "company_metadata" = $Data\r\n                            "associations" = $Data.associations\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }",
            "Type": 19,
            "Start": 6439,
            "Length": 334,
            "StartLine": 149,
            "StartColumn": 35,
            "EndLine": 156,
            "EndColumn": 22
          },
          "DebuggerHidden": false,
          "Id": "e8d77d68-ba17-4727-a973-f5e9b9c80ffe",
          "Ast": {
            "Attributes": "",
            "UsingStatements": "",
            "ParamBlock": "param($Data)",
            "BeginBlock": null,
            "ProcessBlock": null,
            "EndBlock": "param($Data)\r\n                        return @{\r\n                            "company_metadata" = $Data\r\n                            "associations" = $Data.associations\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }",
            "CleanBlock": null,
            "DynamicParamBlock": null,
            "ScriptRequirements": null,
            "Extent": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "company_metadata" = $Data\r\n                            "associations" = $Data.associations\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }",
            "Parent": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "company_metadata" = $Data\r\n                            "associations" = $Data.associations\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }"
          }
        },
        "path": "properties/company-associations.json"
      }
    ]
  },
  "data_extraction": {
    "workflow_filters": [
      "*association*"
    ],
    "form_filters": [],
    "module_filters": [],
    "asset_filters": [
      "*company*"
    ],
    "schema_objects": [
      "companies",
      "hj_projects",
      "contacts"
    ]
  },
  "reporting": {
    "metrics": [
      {
        "name": "company_properties_found",
        "source": "companies_metadata",
        "property": "properties"
      },
      {
        "name": "associations_found",
        "source": "companies_metadata",
        "property": "associations"
      }
    ],
    "include_issues": true,
    "include_data_summary": true
  }
}
}

# Execute the agent template
 $sharedPath = Resolve-Path "$scriptPath/../../../../shared"
& $templatePath -AgentName "company_associations" -Phase "02_timesheet_creation" -Action $Action -Configuration $Configuration


