# Agent Execution Script - project_configuration
# Generated by Agent Factory for Phase: timesheet_creation
# Generated: 2025-09-18 15:06:29

param(
    [Parameter(Mandatory=$false)]
    [string]$Action = "execute"
)

# Import shared utilities
$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$sharedPath = Resolve-Path "$scriptPath/../../../../shared"
Import-Module "$sharedPath/agent-utilities.psm1" -Force

# Agent configuration
$Configuration = @{
{
  "processing": {
    "validation_rules": [
      {
        "parameters": {
          "Metadata": "hj_projects_metadata",
          "ObjectName": "HJ Projects"
        },
        "type": "required_properties"
      },
      {
        "parameters": {
          "DataName": "project assets",
          "Data": "assets_*project*"
        },
        "type": "required_data"
      }
    ],
    "create_directories": [
      "properties",
      "assets",
      "workflows",
      "backend",
      "frontend"
    ],
    "output_files": [
      {
        "data_source": "hj_projects_metadata",
        "transform": {
          "Attributes": [],
          "File": "D:\\code\\hjpshubspot\\analysis\\\\timesheet_process\\\\shared\\agent-configurations.ps1",
          "IsFilter": false,
          "IsConfiguration": false,
          "Module": null,
          "StartPosition": {
            "Content": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "hj_projects_metadata" = $Data\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }",
            "Type": 19,
            "Start": 822,
            "Length": 273,
            "StartLine": 20,
            "StartColumn": 35,
            "EndLine": 26,
            "EndColumn": 22
          },
          "DebuggerHidden": false,
          "Id": "676da983-8f10-4bd3-9a0c-ce6879315a9f",
          "Ast": {
            "Attributes": "",
            "UsingStatements": "",
            "ParamBlock": "param($Data)",
            "BeginBlock": null,
            "ProcessBlock": null,
            "EndBlock": "param($Data)\r\n                        return @{\r\n                            "hj_projects_metadata" = $Data\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }",
            "CleanBlock": null,
            "DynamicParamBlock": null,
            "ScriptRequirements": null,
            "Extent": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "hj_projects_metadata" = $Data\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }",
            "Parent": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "hj_projects_metadata" = $Data\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }"
          }
        },
        "path": "properties/property-mapping.json"
      },
      {
        "data_source": "assets_*project*",
        "transform": {
          "Attributes": [],
          "File": "D:\\code\\hjpshubspot\\analysis\\\\timesheet_process\\\\shared\\agent-configurations.ps1",
          "IsFilter": false,
          "IsConfiguration": false,
          "Module": null,
          "StartPosition": {
            "Content": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "workflows" = $Data | Where-Object { $_.Type -eq "Workflow" }\r\n                            "modules" = $Data | Where-Object { $_.Type -eq "Module" }\r\n                            "forms" = $Data | Where-Object { $_.Type -eq "Form" }\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }",
            "Type": 19,
            "Start": 1287,
            "Length": 474,
            "StartLine": 31,
            "StartColumn": 35,
            "EndLine": 39,
            "EndColumn": 22
          },
          "DebuggerHidden": false,
          "Id": "7fbf498d-c467-4894-bf66-00d0c60d2ff9",
          "Ast": {
            "Attributes": "",
            "UsingStatements": "",
            "ParamBlock": "param($Data)",
            "BeginBlock": null,
            "ProcessBlock": null,
            "EndBlock": "param($Data)\r\n                        return @{\r\n                            "workflows" = $Data | Where-Object { $_.Type -eq "Workflow" }\r\n                            "modules" = $Data | Where-Object { $_.Type -eq "Module" }\r\n                            "forms" = $Data | Where-Object { $_.Type -eq "Form" }\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }",
            "CleanBlock": null,
            "DynamicParamBlock": null,
            "ScriptRequirements": null,
            "Extent": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "workflows" = $Data | Where-Object { $_.Type -eq "Workflow" }\r\n                            "modules" = $Data | Where-Object { $_.Type -eq "Module" }\r\n                            "forms" = $Data | Where-Object { $_.Type -eq "Form" }\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }",
            "Parent": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "workflows" = $Data | Where-Object { $_.Type -eq "Workflow" }\r\n                            "modules" = $Data | Where-Object { $_.Type -eq "Module" }\r\n                            "forms" = $Data | Where-Object { $_.Type -eq "Form" }\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }"
          }
        },
        "path": "assets/asset-inventory.json"
      }
    ]
  },
  "data_extraction": {
    "workflow_filters": [],
    "form_filters": [],
    "module_filters": [],
    "asset_filters": [
      "*project*"
    ],
    "schema_objects": [
      "hj_projects",
      "contacts",
      "companies",
      "deals"
    ]
  },
  "reporting": {
    "metrics": [
      {
        "name": "project_properties_found",
        "source": "hj_projects_metadata",
        "property": "properties"
      },
      {
        "name": "contact_properties_found",
        "source": "contacts_metadata",
        "property": "properties"
      },
      {
        "name": "company_properties_found",
        "source": "companies_metadata",
        "property": "properties"
      },
      {
        "name": "deal_properties_found",
        "source": "deals_metadata",
        "property": "properties"
      },
      {
        "name": "assets_found",
        "source": "assets_*project*",
        "property": null
      }
    ],
    "include_issues": true,
    "include_data_summary": true
  }
}
}

# Execute the agent template
 $sharedPath = Resolve-Path "$scriptPath/../../../../shared"
& $templatePath -AgentName "project_configuration" -Phase "02_timesheet_creation" -Action $Action -Configuration $Configuration


