# Agent Execution Script - approver_assignment
# Generated by Agent Factory for Phase: timesheet_creation
# Generated: 2025-09-18 15:06:29

param(
    [Parameter(Mandatory=$false)]
    [string]$Action = "execute"
)

# Import shared utilities
$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$sharedPath = Resolve-Path "$scriptPath/../../../../shared"
Import-Module "$sharedPath/agent-utilities.psm1" -Force

# Agent configuration
$Configuration = @{
{
  "processing": {
    "validation_rules": [
      {
        "parameters": {
          "Metadata": "contacts_metadata",
          "ObjectName": "Contacts"
        },
        "type": "required_properties"
      },
      {
        "parameters": {
          "Workflows": "workflows_*567500453*",
          "WorkflowType": "approval"
        },
        "type": "required_workflows"
      }
    ],
    "create_directories": [
      "properties",
      "workflows",
      "backend",
      "frontend"
    ],
    "output_files": [
      {
        "data_source": "contacts_metadata",
        "transform": {
          "Attributes": [],
          "File": "D:\\code\\hjpshubspot\\analysis\\\\timesheet_process\\\\shared\\agent-configurations.ps1",
          "IsFilter": false,
          "IsConfiguration": false,
          "Module": null,
          "StartPosition": {
            "Content": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "contact_approver_properties" = $Data.properties\r\n                            "approval_workflows" = $Data.workflows\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }",
            "Type": 19,
            "Start": 3800,
            "Length": 359,
            "StartLine": 86,
            "StartColumn": 35,
            "EndLine": 93,
            "EndColumn": 22
          },
          "DebuggerHidden": false,
          "Id": "9ee64c28-16e6-483b-bfc6-5b670d4deb85",
          "Ast": {
            "Attributes": "",
            "UsingStatements": "",
            "ParamBlock": "param($Data)",
            "BeginBlock": null,
            "ProcessBlock": null,
            "EndBlock": "param($Data)\r\n                        return @{\r\n                            "contact_approver_properties" = $Data.properties\r\n                            "approval_workflows" = $Data.workflows\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }",
            "CleanBlock": null,
            "DynamicParamBlock": null,
            "ScriptRequirements": null,
            "Extent": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "contact_approver_properties" = $Data.properties\r\n                            "approval_workflows" = $Data.workflows\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }",
            "Parent": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "contact_approver_properties" = $Data.properties\r\n                            "approval_workflows" = $Data.workflows\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }"
          }
        },
        "path": "properties/approver-mapping.json"
      },
      {
        "data_source": "workflows_*567500453*",
        "transform": {
          "Attributes": [],
          "File": "D:\\code\\hjpshubspot\\analysis\\\\timesheet_process\\\\shared\\agent-configurations.ps1",
          "IsFilter": false,
          "IsConfiguration": false,
          "Module": null,
          "StartPosition": {
            "Content": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "approval_workflows" = $Data\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }",
            "Type": 19,
            "Start": 4362,
            "Length": 271,
            "StartLine": 98,
            "StartColumn": 35,
            "EndLine": 104,
            "EndColumn": 22
          },
          "DebuggerHidden": false,
          "Id": "de2d25ee-0c96-4ad6-a113-7f9f4db6feb7",
          "Ast": {
            "Attributes": "",
            "UsingStatements": "",
            "ParamBlock": "param($Data)",
            "BeginBlock": null,
            "ProcessBlock": null,
            "EndBlock": "param($Data)\r\n                        return @{\r\n                            "approval_workflows" = $Data\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }",
            "CleanBlock": null,
            "DynamicParamBlock": null,
            "ScriptRequirements": null,
            "Extent": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "approval_workflows" = $Data\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }",
            "Parent": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "approval_workflows" = $Data\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }"
          }
        },
        "path": "workflows/workflow-inventory.json"
      }
    ]
  },
  "data_extraction": {
    "workflow_filters": [
      "*567500453*",
      "*567466561*",
      "*567463273*"
    ],
    "form_filters": [],
    "module_filters": [
      "*approval*"
    ],
    "asset_filters": [],
    "schema_objects": [
      "contacts",
      "hj_approvals",
      "hj_projects"
    ]
  },
  "reporting": {
    "metrics": [
      {
        "name": "approver_properties_found",
        "source": "contacts_metadata",
        "property": "properties"
      },
      {
        "name": "approval_workflows_found",
        "source": "workflows_*567500453*",
        "property": null
      },
      {
        "name": "approval_modules_found",
        "source": "modules_*approval*",
        "property": null
      }
    ],
    "include_issues": true,
    "include_data_summary": true
  }
}
}

# Execute the agent template
 $sharedPath = Resolve-Path "$scriptPath/../../../../shared"
& $templatePath -AgentName "approver_assignment" -Phase "02_timesheet_creation" -Action $Action -Configuration $Configuration


