# Agent Execution Script - workflow_configuration
# Generated by Agent Factory for Phase: timesheet_creation
# Generated: 2025-09-18 15:06:29

param(
    [Parameter(Mandatory=$false)]
    [string]$Action = "execute"
)

# Import shared utilities
$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$sharedPath = Resolve-Path "$scriptPath/../../../../shared"
Import-Module "$sharedPath/agent-utilities.psm1" -Force

# Agent configuration
$Configuration = @{
{
  "processing": {
    "validation_rules": [
      {
        "parameters": {
          "Workflows": "workflows_*567500453*",
          "WorkflowType": "approval"
        },
        "type": "required_workflows"
      }
    ],
    "create_directories": [
      "workflows",
      "backend",
      "frontend"
    ],
    "output_files": [
      {
        "data_source": "workflows_*567500453*",
        "transform": {
          "Attributes": [],
          "File": "D:\\code\\hjpshubspot\\analysis\\\\timesheet_process\\\\shared\\agent-configurations.ps1",
          "IsFilter": false,
          "IsConfiguration": false,
          "Module": null,
          "StartPosition": {
            "Content": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "approval_workflows" = $Data\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }",
            "Type": 19,
            "Start": 8175,
            "Length": 271,
            "StartLine": 193,
            "StartColumn": 35,
            "EndLine": 199,
            "EndColumn": 22
          },
          "DebuggerHidden": false,
          "Id": "814c2e9d-57f0-4fcc-a104-1ae12ccd1e1d",
          "Ast": {
            "Attributes": "",
            "UsingStatements": "",
            "ParamBlock": "param($Data)",
            "BeginBlock": null,
            "ProcessBlock": null,
            "EndBlock": "param($Data)\r\n                        return @{\r\n                            "approval_workflows" = $Data\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }",
            "CleanBlock": null,
            "DynamicParamBlock": null,
            "ScriptRequirements": null,
            "Extent": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "approval_workflows" = $Data\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }",
            "Parent": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "approval_workflows" = $Data\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }"
          }
        },
        "path": "workflows/workflow-configuration.json"
      }
    ]
  },
  "data_extraction": {
    "workflow_filters": [
      "*567500453*",
      "*567466561*",
      "*567463273*"
    ],
    "form_filters": [],
    "module_filters": [
      "*workflow*"
    ],
    "asset_filters": [],
    "schema_objects": []
  },
  "reporting": {
    "metrics": [
      {
        "name": "approval_workflows_found",
        "source": "workflows_*567500453*",
        "property": null
      },
      {
        "name": "reminder_workflows_found",
        "source": "workflows_*567466561*",
        "property": null
      },
      {
        "name": "response_workflows_found",
        "source": "workflows_*567463273*",
        "property": null
      }
    ],
    "include_issues": true,
    "include_data_summary": true
  }
}
}

# Execute the agent template
 $sharedPath = Resolve-Path "$scriptPath/../../../../shared"
& $templatePath -AgentName "workflow_configuration" -Phase "02_timesheet_creation" -Action $Action -Configuration $Configuration


