# Agent Execution Script - data_relationships
# Generated by Agent Factory for Phase: timesheet_creation
# Generated: 2025-09-18 15:06:29

param(
    [Parameter(Mandatory=$false)]
    [string]$Action = "execute"
)

# Import shared utilities
$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
$sharedPath = Resolve-Path "$scriptPath/../../../../shared"
Import-Module "$sharedPath/agent-utilities.psm1" -Force

# Agent configuration
$Configuration = @{
{
  "processing": {
    "validation_rules": [
      {
        "parameters": {
          "Metadata": "hj_projects_metadata",
          "ObjectName": "HJ Projects"
        },
        "type": "required_properties"
      }
    ],
    "create_directories": [
      "properties",
      "backend",
      "frontend"
    ],
    "output_files": [
      {
        "data_source": "hj_projects_metadata",
        "transform": {
          "Attributes": [],
          "File": "D:\\code\\hjpshubspot\\analysis\\\\timesheet_process\\\\shared\\agent-configurations.ps1",
          "IsFilter": false,
          "IsConfiguration": false,
          "Module": null,
          "StartPosition": {
            "Content": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "object_relationships" = @{\r\n                                "hj_projects" = $Data.associations\r\n                            }\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }",
            "Type": 19,
            "Start": 9981,
            "Length": 369,
            "StartLine": 237,
            "StartColumn": 35,
            "EndLine": 245,
            "EndColumn": 22
          },
          "DebuggerHidden": false,
          "Id": "a33a1db0-9fc1-4f0a-b0cd-689083d94f8f",
          "Ast": {
            "Attributes": "",
            "UsingStatements": "",
            "ParamBlock": "param($Data)",
            "BeginBlock": null,
            "ProcessBlock": null,
            "EndBlock": "param($Data)\r\n                        return @{\r\n                            "object_relationships" = @{\r\n                                "hj_projects" = $Data.associations\r\n                            }\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }",
            "CleanBlock": null,
            "DynamicParamBlock": null,
            "ScriptRequirements": null,
            "Extent": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "object_relationships" = @{\r\n                                "hj_projects" = $Data.associations\r\n                            }\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }",
            "Parent": "{\r\n                        param($Data)\r\n                        return @{\r\n                            "object_relationships" = @{\r\n                                "hj_projects" = $Data.associations\r\n                            }\r\n                            "last_updated" = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")\r\n                        }\r\n                    }"
          }
        },
        "path": "properties/data-relationships.json"
      }
    ]
  },
  "data_extraction": {
    "workflow_filters": [],
    "form_filters": [],
    "module_filters": [],
    "asset_filters": [],
    "schema_objects": [
      "hj_projects",
      "contacts",
      "companies",
      "deals",
      "hj_approvals",
      "hj_timesheets"
    ]
  },
  "reporting": {
    "metrics": [
      {
        "name": "object_types_processed",
        "source": "hj_projects_metadata",
        "property": null
      },
      {
        "name": "associations_found",
        "source": "hj_projects_metadata",
        "property": "associations"
      }
    ],
    "include_issues": true,
    "include_data_summary": true
  }
}
}

# Execute the agent template
 $sharedPath = Resolve-Path "$scriptPath/../../../../shared"
& $templatePath -AgentName "data_relationships" -Phase "02_timesheet_creation" -Action $Action -Configuration $Configuration


